export const PATHS = {
    APPRECIATION_COLUMNS_GET: '/api/appreciations/all',
    APPRECIATION_COLUMNS_SAVE: '/api/operations/calculation-appreciations',
    APPRECIATION_DOWNLOAD: '/api/spreadsheets/appre-model',
    APPRECIATION_MODEL: '/api/appreciations-process/all',
    CREATE_ACCOUNT: '/api/auth/register',
    DASHBOARD_GET: '/api/dashboard/all',
    LOGIN: '/api/auth/login',
    PARAMS_EDIT: '/api/parameters',
    PARAMS_GET: '/api/parameters/all',
    PRICE_DELETE: '/api/operations',
    PRICE_LIST_DOWNLOAD: '/api/spreadsheets/depts-status',
    PRICE_LIST_GET: '/api/departments/all',
    PRICE_LIST_REGISTER_ADJUSTMENT_PRICE_1: '/api/operations/price-adjustment-1',
    PRICE_LIST_REGISTER_ADJUSTMENT_PRICE_2: '/api/operations/price-adjustment-2',
    PRICE_LIST_REGISTER_DEPRECIATION: '/api/operations/depreciation-by-department',
    PRICE_LIST_REGISTER_SALE: '/api/operations/sale-of-department',
    PRICE_LIST_UPLOAD: '/api/uploads',
    PRICE_LIST: '/api/departments',
    RECOVERY_PASS_MAIL: '/api/auth/forgot-password',
    RECOVERY_PASS_SET_NEW: '/api/auth/reset-password',
    CHANGE_PASSWORD: '/api/auth/change-password',
    REVENUE_MODEL_GET: '/api/revenue-model/all',
}